### ISSUE TITLE
Feature to remember Dark Mode choices 

### ISSUE THREAD

**Issue by Tibinsunny** [CodeVisors/codevisor-profile-launcher#13]
Hey,
It will be nice if extension could remember users theme preference . Currently when I switch to dark mode and re click on the extension it automatically changes to Normal Mode.

It will be nice if extension could remember user preference .

I am currently working on it and will soon make a Pull request with this feature . Is it okay?

**Comment by AnkushSinghGandhi** [comment]
Closing this issue thanx for your contribution :+1:
